### ISSUE TITLE
window.Payline is not reactive

### ISSUE THREAD

**Issue by Tofandel** [playmoweb/vue-payline-wrapper#2]
window.Payline is not reactive so the payline computed property never updates with a value after loading.. So the lib doesn't work, it never loads properly

**Comment by c4software** [comment]
Strange we use the library internally without any issue. But your addition is great.

**Comment by Tofandel** [comment]
Maybe you include the payline scripts in some other way? Like directly in the head or before loading the component, as that's the only way it would work

**Comment by c4software** [comment]
The `window.Payline` is globally available. there is no real need to have it reactive, since is never really change. In our use case its not a problem.

But maybe its needed for you.

PS: Nop the payline script is injected at runtime.
PS2: Maybe its due to an different version of the payline SDK or Vue version…

**Comment by Tofandel** [comment]
Well it did need to be reactive because it's used in a computed property, and so initially window.Payline is null, and then gets defined when the payline lib is loaded (with loadPayline)

But the problem stems from the fact that window properties are not reactive and the computed property never updates, so if window.Payline is null when loading the component, when the component loads the lib manually the local payline variable is still null

Anyways, issue is fixed now
